### ISSUE TITLE
How to append to the front page?

### ISSUE THREAD

**Issue by JPustkuchen** [cnb/News_Manager-getsimplecms#227]
Hello and thanks a lot for your great module!

We'd like to show the latest news on our front page, which works great. But currently the normal front page content is being overridden by the news so the normal front page content does not get displayed, but should be displayed above. Is there an option or a trick to do this?

**Comment by cnb** [comment]
Currently there's no option for this, but I have in mind adding it - I just haven't decided how it would be.

To display the page content before the posts, you can insert this in your template, just before the `<?php get_page_content(); ?>` line:
```php
<?php if (nm_is_home()) getPageContent(return_page_slug()); ?>
```

If you want the content in all news pages (archives, tag pages, etc.), it would be:
```php
<?php if (nm_is_site()) getPageContent(return_page_slug()); ?>
```

(also with `nm_is_main()` you can do it for the first news page and also page 2, 3, ...)
